export const EXAMPLE_CASES = {
  'reklamnyy-kreativ-dlya-kosmetiki': {
    path: '/examples/reklamnyy-kreativ-dlya-kosmetiki',
    title: 'Рекламный креатив для косметики',
    description: 'Пример AI-креатива для косметики: обычное фото продукта превращается в аккуратный промо-визуал.',
    niche: 'Косметика',
    platform: 'Реклама и маркетплейсы',
    beforeImage: '/examples/cosmetics_before.webp',
    afterImage: '/examples/cosmetics_after.webp',
    relatedTool: '/tools/reklama-dlya-kosmetiki',
    summary: 'Beauty-товарам нужна чистая, премиальная и понятная подача. Такой формат помогает показать упаковку, настроение и визуальную ценность продукта.',
    useCases: ['Карточка товара', 'Промо-пост', 'Рекламный баннер'],
    caption: 'Было обычное фото косметики. Сделали рекламный визуал с более чистой подачей, фокусом на продукте и премиальным настроением.',
    hashtags: ['#косметика', '#рекламныйкреатив', '#нейросеть', '#adgena'],
  },
  'kartochka-dlya-odezhdy': {
    path: '/examples/kartochka-dlya-odezhdy',
    title: 'Карточка товара для одежды',
    description: 'Пример AI-карточки для одежды: чистая композиция, акцент на товаре и визуал для маркетплейса.',
    niche: 'Одежда',
    platform: 'Wildberries / Ozon',
    beforeImage: '/examples/clothes_before.webp',
    afterImage: '/examples/clothes_after.webp',
    relatedTool: '/tools/reklama-dlya-odezhdy',
    summary: 'Для одежды важно быстро показать форму, цвет и стиль. AI-визуал помогает сделать карточку заметнее и подготовить несколько гипотез.',
    useCases: ['Карточка WB', 'Карточка Ozon', 'Fashion-промо'],
    caption: 'Из обычного фото одежды сделали более аккуратную карточку для каталога и рекламы.',
    hashtags: ['#одежда', '#wildberries', '#карточкатовара', '#adgena'],
  },
  'promo-dlya-edy': {
    path: '/examples/promo-dlya-edy',
    title: 'Промо-визуал для еды',
    description: 'Пример рекламного визуала для еды, ресторана или доставки: аппетитная композиция по фото продукта.',
    niche: 'Еда и рестораны',
    platform: 'Соцсети и доставка',
    beforeImage: '/examples/food_before.webp',
    afterImage: '/examples/food_after.webp',
    relatedTool: '/tools/reklama-dlya-restorana',
    summary: 'Еда должна выглядеть свежо и вызывать желание попробовать. Такой креатив подходит для доставки, меню, постов и промо.',
    useCases: ['Промо доставки', 'Пост в соцсетях', 'Баннер акции'],
    caption: 'Обычное фото блюда превратили в аппетитный промо-визуал для рекламы и соцсетей.',
    hashtags: ['#ресторан', '#доставкаеды', '#foodpromo', '#adgena'],
  },
  'kreativ-dlya-gadzheta': {
    path: '/examples/kreativ-dlya-gadzheta',
    title: 'Креатив для гаджета',
    description: 'Пример AI-креатива для электроники и аксессуаров: товар показан в более понятном сценарии использования.',
    niche: 'Гаджеты',
    platform: 'VK / Telegram Ads',
    beforeImage: '/examples/gadgets_before.webp',
    afterImage: '/examples/gadgets_after.webp',
    relatedTool: '/tools/kreativ-dlya-vk-reklamy',
    summary: 'Для гаджетов полезно показать не только внешний вид, но и сценарий применения. Это делает рекламный смысл быстрее и понятнее.',
    useCases: ['VK реклама', 'Telegram Ads', 'Карточка товара'],
    caption: 'Сделали рекламный визуал для гаджета: больше контекста, понятнее сценарий, товар в центре.',
    hashtags: ['#гаджеты', '#vkreklama', '#telegramads', '#adgena'],
  },
  'vizual-dlya-tovarov-doma': {
    path: '/examples/vizual-dlya-tovarov-doma',
    title: 'Визуал для товаров для дома',
    description: 'Пример AI-визуала для мебели, декора и товаров для дома в интерьерной подаче.',
    niche: 'Дом и интерьер',
    platform: 'Маркетплейсы и реклама',
    beforeImage: '/examples/home_before.webp',
    afterImage: '/examples/home_after.webp',
    relatedTool: '/tools/reklama-dlya-mebeli',
    summary: 'Товары для дома легче продавать, когда покупатель видит их в пространстве. Интерьерная подача помогает быстрее представить результат.',
    useCases: ['Карточка Ozon', 'Промо мебели', 'Пост бренда'],
    caption: 'Показали товар для дома в более живой интерьерной подаче с помощью AI.',
    hashtags: ['#интерьер', '#мебель', '#товарыдлядома', '#adgena'],
  },
  'reklama-dlya-aksessuarov': {
    path: '/examples/reklama-dlya-aksessuarov',
    title: 'Реклама для аксессуаров',
    description: 'Пример рекламного AI-визуала для аксессуаров, подарков и небольших товаров.',
    niche: 'Аксессуары',
    platform: 'Соцсети и маркетплейсы',
    beforeImage: '/examples/accessories_before.webp',
    afterImage: '/examples/accessories_after.webp',
    relatedTool: '/tools/promo-banner-dlya-tovara',
    summary: 'Небольшим товарам нужна аккуратная композиция и сильный визуальный акцент. Такой креатив помогает выделить продукт в ленте или каталоге.',
    useCases: ['Промо-пост', 'Карточка товара', 'Рекламный баннер'],
    caption: 'Обычное фото аксессуара превратили в аккуратный рекламный визуал для соцсетей и маркетплейсов.',
    hashtags: ['#аксессуары', '#баннер', '#маркетплейсы', '#adgena'],
  },
};

export const EXAMPLE_CASE_SLUGS = Object.keys(EXAMPLE_CASES);
